name: Build
on:
  push:
    branches-ignore:
      - debian
      - khronos-registry
jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-18.04
          - macos-10.15
        compiler:
          - gcc
          - clang
        build-opts:
          - ''
          - '-Dglx=no'
          - '-Degl=no'
          - '-Dx11=false'
        exclude:
          - os: macos-10.15
            compiler: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - if: runner.os == 'macOS'
        run: brew install ninja
      - if: runner.os == 'Linux'
        run: >
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends
          libgl1-mesa-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          libgl1-mesa-dri
          ninja-build
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          pip3 install meson
      - if: runner.os == 'macOS'
        run: /bin/sh -c "CC=${{ matrix.compiler }} .github/scripts/epoxy-ci-osx.sh ${{ matrix.build-opts }}"
      - if: runner.os == 'Linux'
        run: /bin/sh -c "CC=${{ matrix.compiler }} .github/scripts/epoxy-ci-linux.sh ${{ matrix.build-opts }}"
